# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "aimmo-mlops-terraform-backend"
    dynamodb_table = "terraform-backend-lock"
    encrypt        = true
    key            = "tutorial/shelley/terraform.tfstate"
    region         = "ap-northeast-2"
  }
}
